### ISSUE TITLE
v2.2 on PyPI missing try/except for pypandoc import

### ISSUE THREAD

**Issue by drien** [aljungberg/hexahexacontadecimal#1]
Installs of v2.2 from pypi fail on systems without `pypandoc` installed, since the setup.py in the pypi package seems to be missing the try/except found here: 

https://github.com/aljungberg/hexahexacontadecimal/blob/6820cbfb0847955d5431a8080935ccb0ae58659a/setup.py#L3-L9

The version from pypi (https://files.pythonhosted.org/packages/eb/14/1d72ec5704a19dd42cb64ee3d85f3070c3b2836529e0ca0c69190a429fcf/hexahexacontadecimal-2.2.tar.gz) looks like this:

```python
import setuptools

import pypandoc
# This bit requires pandoc. On Mac OS X:
#   brew install haskell-platform && cabal update && cabal install pandoc
description = pypandoc.convert('README.md', 'rst', format='markdown')
```

Since the github versions still have the try/except I assume this was just a packaging issue but I figured I'd give a heads up.

Thanks for open sourcing this by the way, I very much appreciate the effort to document and package it–I've had it in production for a year and have generated nearly 20 million short urls with it! 👍

**Comment by aljungberg** [comment]
Just saw that I never responded to this. You're absolutely right and I fixed it in the 2.2.1 release. I just downloaded the tgz from pypi to double-check and it looks good. Thanks for the report!

Glad you like it. We're making millions of neat and optimally compact API URLs too!
